spring.application.name=Sistema de Eventos Acessiveis

# Dados de conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/eventos_acessiveis
spring.datasource.username=teh
spring.datasource.password=1878
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desabilitar o aviso do Open-In-View
spring.jpa.open-in-view=false
