spring.application.name=aula03

# 1. Banco em ARQUIVO (conforme solicitado no exercício)
# O ponto indica a raiz do projeto no seu Pop!_OS
spring.datasource.url=jdbc:h2:file:./h2/banco
spring.datasource.username=sa
# Recomendo deixar vazio para facilitar no exercício, ou lembre de digitar no console
spring.datasource.password=1234
spring.datasource.driver-class-name=org.h2.Driver

# 2. Configurações de JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
# Importante para o H2 não se perder com as sequências do Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# 3. H2 Console (A interface visual)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Permite que o console seja exibido dentro de frames (necessário para alguns navegadores)
spring.h2.console.settings.web-allow-others=true